repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: flake8
        args:
            - --ignore=E501
    -   id: check-docstring-first
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.6.0
    hooks:
    -   id: reorder-python-imports
        language_version: python3
        args:
        - --separate-relative
        - --separate-from-import
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.21.0
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/Botpy/pre-commit-pylint.git
    rev: v0.0.3
    hooks:
    -   id: pylint-score-limit
        args:
        - --limit=8.5
        - --rcfile=/.pylintrc